### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Mast3rChief** [snOOrz/homebridge-aqara#10]
Hey guys,

first of all a huge thanks for implementing such an awesome tool.

I ran into some problems when starting homebridge. I installed everything as described in the README. When I'm executing 

`homebridge`

I get this

```
Loaded plugin: homebridge-aqara
/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:4
const iv = Buffer.from([0x17, 0x99, 0x6d, 0x09, 0x3d, 0x28, 0xdd, 0xb3, 0xba, 0x69, 0x5a, 0x2e, 0x6f, 0x58, 0x56, 0x2e]);
                  ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:4:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-aqara/index.js:2:3)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:147:14)

```

I tried other plugins and they work fine.
Thanks for your help!

Some more info:
node -v    4.3.2
npm -v     3.10.9
raspbian jessy

**Comment by Sagwed** [comment]
update node to 5.x
node 5.11.1 work for me
