### ISSUE TITLE
Aqara device not viewed on homekit with homebridge

### ISSUE THREAD

**Issue by garvarma** [snOOrz/homebridge-aqara#20]
Hi, 
I tried to incorporate the aqara devices (gateway, door sensor and motion sensor) into homekit, using homebridge, but when i tried, homekit says that there is no device to add.

I installed the npm homebridge-aqara

I obtained mac address of aqara gateway and password and added on my config.json like this:

> 	pi@raspberrypi:~/.homebridge $ more config.json
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51825,
        "pin": "031-45-154"
    },

    "platforms": [
        {
            "platform" : "yeelight",
            "name" : "yeelight"
        },
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://192.168.0.100:8123",
            "password": "XXXXXX",
            "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "s
ensor", "switch"]
        },
        {
            "platform": "AqaraPlatform",
            "sid": ["MAC_ADDRESS_GW"],
            "password": ["xxxxxxxx"]
        }

    ]

}> 

And when i execute homebridge i have this message: 

/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:55
    var gatewaySid = this.gatewaySids[accessory.UUID];
                                               ^

TypeError: Cannot read property 'UUID' of undefined
    at AqaraAccessoryFactory.autoRemoveAccessory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:55:48)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:92:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

Just say that in config.json about "sid" i added the mac address in this format: "aabbccddeeff"

Can someone help me please?

thanks

**Comment by snOOrz** [comment]
The accessory object is not defined, not sure why this could happen. You can clean cached data by deleting ~/.homebridge/accessories/cachedAccessories and restart homebridge.

On 11 Dec 2016, 18:21 +0800, garvarma <notifications@github.com>, wrote:

Hi,
I tried to incorporate the aqara devices (gateway, door sensor and motion sensor) into homekit, using homebridge, but when i tried, homekit says that there is no device to add.

I installed the npm homebridge-aqara

I obtained mac address of aqara gateway and password and added on my config.json like this:

pi@raspberrypi:~/.homebridge $ more config.json
{
"bridge": {
"name": "Homebridge",
"username": "XX:XX:XX:XX:XX:XX",
"port": 51825,
"pin": "031-45-154"
},


"platforms": [
    {
        "platform" : "yeelight",
        "name" : "yeelight"
    },
    {
        "platform": "HomeAssistant",
        "name": "HomeAssistant",
        "host": "http://192.168.0.100:8123",
        "password": "XXXXXX",
        "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "s



ensor", "switch"]
},
{
"platform": "AqaraPlatform",
"sid": ["MAC_ADDRESS_GW"],
"password": ["xxxxxxxx"]
}


]



}>

And when i execute homebridge i have this message:

/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:55
var gatewaySid = this.gatewaySids[accessory.UUID];
^

TypeError: Cannot read property 'UUID' of undefined
at AqaraAccessoryFactory.autoRemoveAccessory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:55:48)
at Timeout._onTimeout (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:92:15)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)

Just say that in config.json about "sid" i added the mac address in this format: "aabbccddeeff"

Can someone help me please?

thanks

**Comment by garvarma** [comment]
Hi,
After deleting myHome in homekit, and the file that you told me, now when i begin again in homekit, appears me and accesory called homebridge, but don't do anything not appear door sensor or motion sensor. 
Maybe i need to configure the accesories? Why only appear the device Hombridge?

thanks

**Comment by snOOrz** [comment]
You need to configure your accessories again. First add homebridge, then follow the steps to add all accessories.

On 11 Dec 2016, 19:24 +0800, garvarma <notifications@github.com>, wrote:

Hi,
After deleting myHome in homekit, and the file that you told me, now when i begin again in homekit, appears me and accesory called homebridge, but don't do anything not appear door sensor or motion sensor.
Maybe i need to configure the accesories? Why only appear the device Hombridge?

thanks

**Comment by garvarma** [comment]
Hi, 
thanks for reply. 
Please can you share to me link, where explains the steps to add all accesories? because i didn't find any place.

thanks

**Comment by snOOrz** [comment]
After you add the homebridge to HomeKit in iOS Home app, all the devices under homebridge will popup automatically. If you can’t see those devices, may be you need to verify how many devies are connected in the homebridge’s details page.

On 11 Dec 2016, 19:55 +0800, garvarma <notifications@github.com>, wrote:

Hi,
thanks for reply.
Please can you share to me link, where explains the steps to add all accesories? because i didn't find any place.

thanks

**Comment by garvarma** [comment]
Hi, 

I think that i solve the problem, now yeelight and aqara devices appears.

The problem i think was that i have 2 networks, in 1 network was raspi with homebridge, and in other network was devices of aqara and yeelight.

Well i will continue trying different options.

thanks

**Comment by marcotini** [comment]
@garvarma did you solve? Because I'm not. I'm add the MAC address and the password but nothing happen. When I start the Homebridge simply appear:

> [12/19/2016, 8:03:19 PM] Loaded plugin: homebridge-aqara
> [12/19/2016, 8:03:19 PM] Registering platform 'homebridge-aqara.AqaraPlatform'

But in the app Home nothing happen!

**Comment by garvarma** [comment]
@marcotini,
Yes i resolved. The problem was that i had the ipad( that works with honekit like bridge) in other network, where devices are.

After i put all in the same network, then devoces apoeared automatically
