### ISSUE TITLE
homebridge crash, TypeError: Cannot read property 'UUID' of undefined

### ISSUE THREAD

**Issue by hicaoc** [snOOrz/homebridge-aqara#39]
/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:56
    var gatewaySid = this.gatewaySids[accessory.UUID];
                                               ^

TypeError: Cannot read property 'UUID' of undefined
    at AqaraAccessoryFactory.autoRemoveAccessory (/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:56:48)
    at Timeout._onTimeout (/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:92:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by Jacbao** [comment]
Experienced same issue. 
my env is no accessory used, i'm just link Xiaomi gatway for testing.

**Comment by Boms** [comment]
Same issue.
I run homebridge on raspberrypi. It work right with system boot, but homebridge crash after a half hour.
