### ISSUE TITLE
 TypeError: Cannot read property 'sid' of null

### ISSUE THREAD

**Issue by flamework1986** [snOOrz/homebridge-aqara#59]
Hello. Cant start Aqara with this error:
`Load homebridge-aquara.AquaraPlatform
C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-aquara\lib\AquaraPlatform.js:61
  var sid = config['sid'];
                  ^

TypeError: Cannot read property 'sid' of null
    at AquaraPlatform.loadConfig (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-aquara\lib\AquaraPlatform.js:61:19)
    at new AquaraPlatform (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-aquara\lib\AquaraPlatform.js:50:8)
    at Server._loadDynamicPlatforms (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:315:30)
    at Server.run (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:82:8)
    at module.exports (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load `(module.js:314:12)`
My config:
"bridge": {
        "name": "HomeBridge",
        "username": "CC:22:3D:E3:00:00",
        "port": 51826,
        "pin": "031-00-00"
    },
    
   "platforms": [ {
    "platform": "AqaraPlatform",
    "fakeLightBulbForLightSwitch": true,
    "sid": [ "00:00:07:89:1D:A7" ],
         "password": [ "B9A1B03800000000" ]
     }],
    "description": "HomeBridge HTTP Status Control",
    "accessories": [ {
	        "accessory": "Http",
                "name": "Alfresco Lamp",
			"switchHandling": "realtime",
				"http_method": "GET",
				"on_url":      "http://localhost/controller/1700/ON",
				"off_url":     "http://localhost/controller/1700/OFF",
				"status_url":  "http://localhost/status/100059",				
			"service": "Light",
				"brightnessHandling": "yes",
				"brightness_url":     "http://localhost/controller/1707/%b",
				"brightnesslvl_url":  "http://localhost/status/100054"			
									    
       
}]}

**Comment by flamework1986** [comment]
Update to 12 version - no way :(

**Comment by derekhuangxu** [comment]
hey,have you resolved this problem?
