### ISSUE TITLE
ReferenceError: service is not defined

### ISSUE THREAD

**Issue by JunlongZhao** [snOOrz/homebridge-aqara#64]
/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:52
     var characteristic = service.getCharacteristic(Characteristic.Name);
                          ^

ReferenceError: service is not defined
    at AqaraAccessoryFactory.configureAccessory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:52:27)
    at AqaraPlatform.configureAccessory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:187:16)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:342:24)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:83:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by richen** [comment]
var Accessory, PlatformAccessory, **Service**, Characteristic, UUIDGen, Factory;
**service**.getCharacteristic(Characteristic.Name);

**Comment by JunlongZhao** [comment]
{
        "platforms": [
        {
            "platform": "AqaraPlatform",
            ...
            "sensor_names": {
				"74ef":"Kitchen Window"
            }
            ...
        }]
    }

It doesn't work

**Comment by KillSwitchSIG** [comment]
I confirm I get the same issue when trying to add the sensor_names part.

**Comment by georgkreimer** [comment]
Especially frustrating with the sensor disappearing bug..
