### ISSUE TITLE
got errors after upgrade node to version v7.10.0

### ISSUE THREAD

**Issue by Stevenyu1982** [snOOrz/homebridge-aqara#80]
Try to get my broadlink RM work with my homekit as well. this require node version to at at least v7.6.0, after upgrade node version to v7.10.0
i got this issue, looks like aqara is not yet compatiable with Node7.10 yet?

anyone has the same issue?

homebridge
[5/26/2017, 5:29:06 PM] Loaded plugin: homebridge-aqara
[5/26/2017, 5:29:06 PM] Registering platform 'homebridge-aqara.AqaraPlatform'
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loaded plugin: homebridge-broadlink-rm
[5/26/2017, 5:29:06 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loaded plugin: homebridge-camera-isight
[5/26/2017, 5:29:06 PM] Registering platform 'homebridge-camera-isight.Camera-iSight'
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loaded plugin: homebridge-homeassistant
[5/26/2017, 5:29:06 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loaded plugin: homebridge-miio
[5/26/2017, 5:29:06 PM] Registering platform 'homebridge-miio.XiaomiMiio'
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loaded config.json with 0 accessories and 1 platforms.
[5/26/2017, 5:29:06 PM] ---
[5/26/2017, 5:29:06 PM] Loading 1 platforms...
[5/26/2017, 5:29:06 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[5/26/2017, 5:29:06 PM] [Broadlink RM] Initializing platform accessory 'Learn'...
[5/26/2017, 5:29:06 PM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[5/26/2017, 5:29:06 PM] [Broadlink RM] Initializing platform accessory 'Auto-off Switch'...
[5/26/2017, 5:29:06 PM] [Broadlink RM] Initializing platform accessory 'TV On/Off'...
[5/26/2017, 5:29:06 PM] Loading 0 accessories...
Load homebridge-aqara.AqaraPlatform
/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26
  if (config['sensor_names']) {
            ^

TypeError: Cannot read property 'sensor_names' of null
    at new AqaraAccessoryFactory (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26:13)
    at new AqaraPlatform (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:27:18)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by timh1004** [comment]
Try deleting ~/.homebridge/accessories/cachedAccessories

**Comment by Stevenyu1982** [comment]
tried, it's the same error

**Comment by licuhui** [comment]
Need to use v 6.X.X

**Comment by Stevenyu1982** [comment]
no idea of nodejs program, anyone can provide some idea, so I may help fix this in Node version 7?

**Comment by jm0477** [comment]
I had the same issue like yours, my solution is uninstall the homebridge-aqara plugin. 
Previously I installed "homebridge-aqara" before homebridge-mi-aqara.
so solution simply is:
sudo npm remove homebridge-aqara then it works for me.
Hope it can be helpful for others.
