### ISSUE TITLE
plugin shuts down homebridge

### ISSUE THREAD

**Issue by theo-69** [snOOrz/homebridge-aqara#82]
After i use one of my aqara switches the plugin and homebridge crashes

`/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 4c66a368-b90f-4c27-8cf1-8cf0978f966f
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:274:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:96:13)
    at API.emit (events.js:191:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at AqaraAccessoryFactory.findServiceAndSetValue (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:232:14)
    at AqaraAccessoryFactory.setLightSwitch (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:145:8)
    at DuplexEightySixSwitchParser.parse (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:395:22)`

**Comment by a900927** [comment]
Try deleting ~/.homebridge/accessories/cachedAccessories
and reinstall the homebridge-aqara

**Comment by theo-69** [comment]
working now, just two button aqara switch is not showing :-(
