### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by theo-69** [snOOrz/homebridge-aqara#85]
Trying to reinstall aqara, always getting:

> TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:4:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-aqara/index.js:2:3)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:150:14)

>

**Comment by theo-69** [comment]
my mistake, found the ERROR
