### ISSUE TITLE
addMembership ENODEV

### ISSUE THREAD

**Issue by rench** [snOOrz/homebridge-aqara#86]
dgram.js:507
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:1018:11)
    at Socket.addMembership (dgram.js:507:11)
    at Socket.<anonymous> (/root/node_modules/homebridge-aqara/lib/AqaraPlatform.js:122:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at _handle.lookup (dgram.js:226:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)

**Comment by theo-69** [comment]
???
