### ISSUE TITLE
run homebridge got error

### ISSUE THREAD

**Issue by lclcheuk** [snOOrz/homebridge-aqara#93]
nodejs v6.11.0

[7/9/2017, 11:32:37 PM] Initializing MiAqaraPlatform platform...
Load homebridge-aqara.AqaraPlatform
/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26
if (config['sensor_names']) {
^

TypeError: Cannot read property 'sensor_names' of null
at new AqaraAccessoryFactory (/usr/lib/node_modules/homebridge-aqara/lib/AqaraAccessoryFactory.js:26:13)
at new AqaraPlatform (/usr/lib/node_modules/homebridge-aqara/lib/AqaraPlatform.js:27:18)
at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:315:30)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:82:8)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object. (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)

**Comment by iCarl** [comment]
Send your config file

**Comment by sephrioth** [comment]
Same error here, running on docker. Is it possible to fix it in node7?

**Comment by greatlkv** [comment]
Hello. Have the same problem

{ 

    "bridge": { 

        "name": "Homebridge", 

        "username": "CC:22:3D:E3:CE:30", 

        "port": 51826, 

        "pin": "031-45-154" 

    },  

"platforms": [

{

"platform": "AqaraPlatform",

"sid": ["7811dcb27176"],

"password": ["99w95kxzub3n897q"]

}]

}
